export * from './student/SHomePage';
export * from './student/SModulesPage';
export * from './student/MultiOpt';
export * from './professor/PHomePage';
export * from './professor/PManage';
export * from './admin/AManage';
export * from './professor/PModulesPage';
export * from './admin/ASyllabus';
export * from './admin/ARequest';
